// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPd7PsSuhF9pYvKmHee1bOWAhNDnqboeQ',
    appId: '1:883439352124:web:37a99495254712216f0639',
    messagingSenderId: '883439352124',
    projectId: 'chatting-app-f2b3b',
    authDomain: 'chatting-app-f2b3b.firebaseapp.com',
    storageBucket: 'chatting-app-f2b3b.firebasestorage.app',
    measurementId: 'G-D1TP06WJ03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBECXK5Dl6o1PFNAxuAZk3laP6bRSXCzIo',
    appId: '1:883439352124:android:502883a82ee8c1446f0639',
    messagingSenderId: '883439352124',
    projectId: 'chatting-app-f2b3b',
    storageBucket: 'chatting-app-f2b3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABogSLa7A8Inn-wO1Hum4euw63PaAx1fA',
    appId: '1:883439352124:ios:7ace2efc5d118bc26f0639',
    messagingSenderId: '883439352124',
    projectId: 'chatting-app-f2b3b',
    storageBucket: 'chatting-app-f2b3b.firebasestorage.app',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPd7PsSuhF9pYvKmHee1bOWAhNDnqboeQ',
    appId: '1:883439352124:web:72ccaff20e3cc72e6f0639',
    messagingSenderId: '883439352124',
    projectId: 'chatting-app-f2b3b',
    authDomain: 'chatting-app-f2b3b.firebaseapp.com',
    storageBucket: 'chatting-app-f2b3b.firebasestorage.app',
    measurementId: 'G-3Q2P3RCC53',
  );
}
